DROP DATABASE IF EXISTS buscadorVuelos;
CREATE DATABASE buscadorVuelos;
USE buscadorVuelos;

	CREATE TABLE AEROPUERTO (
	CodIATA VARCHAR(30),
	Nombre VARCHAR (50),
	Ciudad VARCHAR (30), 
	Pais VARCHAR(50),
 	CONSTRAINT PK_AEROPUERTO PRIMARY KEY(CodIATA,Nombre)

	);

	CREATE TABLE TERMINAL (
	IDterminal char(2) NOT NULL,
	CodIATA VARCHAR(30) NOT NULL,
	CONSTRAINT PK_TERMINAL PRIMARY KEY (IDterminal,CodIATA)

	);	

	CREATE TABLE VUELO (
	CodVuelo CHAR(10),
	CodOACICompañia VARCHAR(30),
	NombreAeropuertoOrigen VARCHAR (50),
	CodIATAOrigen VARCHAR(30),
	IDterminalOrigen VARCHAR (2),
	NombreAeropuertoDestino VARCHAR (50),
	CodIATADestino VARCHAR(30),
	IDterminalDestino VARCHAR (2),
	Estado ENUM ('OnTime', 'Delayed', 'Advance'),
	PRIMARY KEY (CodVuelo),
	CONSTRAINT FK_ORIGEN FOREIGN KEY(CodIATAOrigen,NombreAeropuertoOrigen) 
	REFERENCES AEROPUERTO (CodIATA,Nombre),
	CONSTRAINT FK_TERMINALORIGEN FOREIGN KEY(IDterminalOrigen) 
	REFERENCES TERMINAL (IDterminal),
	CONSTRAINT FK_DESTINO FOREIGN KEY(CodIATADestino,NombreAeropuertoDestino) 
	REFERENCES AEROPUERTO (CodIATA,Nombre),
	CONSTRAINT FK_TERMINALDESTINO FOREIGN KEY(IDterminalDestino) 
	REFERENCES TERMINAL (IDterminal)		

	);

	CREATE TABLE ASIENTO (
	CodAsiento char(20) NOT NULL,
	TipoClase ENUM ('TURISTA', 'BUSSINESS', 'FIRST CLASS'),
	PRIMARY KEY (CodAsiento,TipoClase) 

	);
	
	CREATE TABLE PASAJERO (
	DNI CHAR(20),
	Nombre VARCHAR(20),
	Apellido1 VARCHAR(20),
	Apellido2 VARCHAR(20),
	Libertad ENUM ('si', 'no') NOT null,
	PRIMARY KEY (Nombre,DNI,Libertad) 

	);
	
	
	CREATE TABLE EQUIPAJE (
	CodMaleta CHAR(20),
	dimensiones FLOAT (4) ,
	peso FLOAT (4),
	ubicacion ENUM ('BODEGA', 'CABINA') NOT NULL,
	PRIMARY KEY (CodMaleta), 
	CONSTRAINT FK_MALETA FOREIGN KEY(CodMaleta) 
	REFERENCES PASAJERO (DNI)	

	);

	CREATE TABLE RESERVA (
	Localizador VARCHAR(20) NOT NULL,
	DNI CHAR(30),
	Precio float(4),
	PRIMARY KEY (Localizador,DNI) 

	);

	CREATE TABLE PENAL (
	Nombre VARCHAR(30),
	DNI CHAR(9),
	libre ENUM ('SI','NO')
);

/* MUESTRA LAS TABLAS */
SHOW TABLES;
SELECT * FROM AEROPUERTO;
SELECT * FROM TERMINAL;
SELECT * FROM VUELO;
SELECT * FROM ASIENTO;
SELECT * FROM PASAJERO;
SELECT * FROM EQUIPAJE;
SELECT * FROM RESERVA;
SELECT * FROM PENAL;



